theme: jekyll-theme-slate

title: Meta-heurísticas para o PRVJTFHCES
description: "Métodos meta-heurísticos em Python para o PRVJTFHCES"

author: Helton Gomes
pub_year: 2020
github_username: heltongomes
