title: Meta-heurísticas para o PRVJTFHCES
description: "Métodos meta-heurísticos em Python para o PRVJTFHCES"

author: Helton Gomes
pub_year: 2020
github_username: heltongomes
repo: "https://github.com/heltongomes/meta-heuristicas_PRVJTFHCES/"

url: https://heltongomes.github.io/
baseurl: /meta-heuristicas_PRVJTFHCES

defaults:
  - scope:
      path: ""
    values:
      layout: default

markdown: kramdown

theme: jekyll-theme-time-machine
