theme: jekyll-theme-slate

title: ![EM](/images/logo-em.png) Métodos Meta-heurísticos para a resolução do PRVJTFHCES
description: "Proposta de métodos meta-heurísticos em Python para a resolução do PRVJTFHCES"

author: Helton Gomes
pub_year: 2020
github_username: heltongomes
repo: "https://github.com/heltongomes/meta-heuristicas_PRVJTFHCES/"

url: https://heltongomes.github.io/
baseurl: /meta-heuristicas_PRVJTFHCES

defaults:
  - scope:
      path: ""
    values:
      layout: default

markdown: kramdown
